api:
  encryption:
    key: "G9f/aI69A4cTihEP6WADgwKwV/tBlUcKZ5tWtBDPNkg="

# Enable logging
logger:
  level: DEBUG

ota:
  - platform: esphome
    password: "e33f3bce9e7c0d96946b2b2a2b664c3e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # do not enable, connection may be weak!
  fast_connect: False

web_server:
  port: 80