font:
  - file: "gfonts://Roboto"
    id: font_default
    size: 12
    bpp: 8

  - file:
      type: gfonts
      family: Roboto
      weight: bold
    id: font_default_bold
    size: 12
    bpp: 8

  - file: "gfonts://Roboto"
    id: font_default_large
    size: 14
    bpp: 8

  - file:
      type: gfonts
      family: Roboto
      weight: bold
    id: font_default_large_bold
    size: 14
    bpp: 8

  - file:
      type: gfonts
      family: Roboto
    id: font_default_xlarge
    size: 22
    bpp: 8

  - file:
      type: gfonts
      family: Roboto
      weight: bold
    id: font_default_xlarge_bold
    size: 22
    bpp: 8

  - file:
      type: gfonts
      family: Micro+5
    id: imprint
    size: 11

  - file: 'https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 20
    glyphs:
      - "\U000F0EC4" # remote-off
      - "\U000F0454" # remote
      - "\U000F1835" # battery-sync-outline
      - "\U000F10CD" # battery-alert-variant-outline
      - "\U000F007A" # battery-10
      - "\U000F007B" # battery-20
      - "\U000F007C" # battery-30
      - "\U000F007D" # battery-40
      - "\U000F007E" # battery-50
      - "\U000F007F" # battery-60
      - "\U000F0080" # battery-70
      - "\U000F0081" # battery-80
      - "\U000F0082" # battery-90
      - "\U000F0079" # battery